# Generated by Django 4.1.3 on 2022-12-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='category',
            field=models.CharField(blank=True, choices=[('Online Services', 'Online Services'), ('Travel', 'Travel'), ('Transportation', 'Transporation'), ('Food', 'Food'), ('Insurance', 'Insurance'), ('Entertainment', 'Entertainment'), ('Emergency', 'Emergency'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
