# Generated by Django 4.1.3 on 2022-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expence_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
