# Generated by Django 4.1.3 on 2022-12-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
